#!/bin/bash

echo "Generating PHP documentation from 'src' directory"
echo "-------------------------------------------------"

phpdoc -d ./src -t ./phpdocs  --title "The World Package by Andrew Woods"

